.TH SONIC-PI 1
.SH NAME
sonic-pi \- The Live Coding Synth for Everyone
.SH SYNOPSIS
.B sonic-pi
.SH "DESCRIPTION"
Sonic Pi is a new kind of musical instrument. Instead of strumming
strings or whacking things with sticks - you write code - LIVE.
.PP
This application is the graphical user interface that provides a full
IDE and includes a step-by-step tutorial and a reference manual.
